# Copyright 2024 IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0

FROM quay.io/pypa/manylinux2014_x86_64

RUN python3.11 -m pip install setuptools==69.5.1 pybind11
RUN python3.10 -m pip install setuptools==69.5.1 pybind11
RUN python3.9 -m pip install setuptools==69.5.1 pybind11
RUN python3.12 -m pip install pip wheel setuptools pybind11
RUN python3.13 -m pip install pip wheel setuptools pybind11
